### ISSUE TITLE
no NPC chatbox and teleporting issues

### ISSUE THREAD

**Issue by Nuktos** [friendlyfiregame/friendlyfiregame#22] opened 2020-11-25 19:10 UTC
Hi, to test the gamepad compatibility I just downloaded this windows version of the game from here:
https://github.com/friendlyfiregame/friendlyfiregame/actions/runs/379222937
and unlike the steam current version, no dialogue from npc are seen, only the player's options to answer. The borders of the screen appear as black during the dialogue, the characters move according to their emotions and all, but no speech bubble, no text. That happens with the first fire, the shadow character, the signs,... apparently everything and everybody actually. I also couldn't go far he first time because after accepting the fire quest and trying to cross the bridge, the shadow character didn't let me ask about that, I could only answer "I can't handle this darkness".

OK, I just restarted the game and this time when I talked to shadow guy and when the dialogue started (without his speech bubble), I teleported here: https://cdn.discordapp.com/attachments/765932656655335465/781227911696220220/unknown.png and still was there after the speech. I got the bonus this time.
Another moment where I teleported is here: https://cdn.discordapp.com/attachments/765932656655335465/781232383093112902/unknown.png
 I'm falling in direction of 1 and suddenly I teleport at 2, it happened several times.

On a positive note, I can tell my gamepad seems to work fine(while the current steam version doesn't see a single input from my gamepad), I went to the good boy ending without any problem.

**Comment by headcr4sh** [comment] 2020-11-25 19:33
Hi @Nuktos ,

thanks for reporting back!
The build from 2 days ago unfortunately contains a bug in one of the core functions related to "delaying stuff". That's the reason for the missing texts and stuff.

The bug has been fixed and the latest build can be fetched from here:
https://github.com/friendlyfiregame/friendlyfiregame/actions/runs/383736005

@eduke2k even added the possibility to "pet the dog" as you suggested! :-D

Hope you enjoy the new build, a Steam release should arrive within the next few days.

**Comment by Nuktos** [comment] 2020-11-25 22:37
OK, I downloaded it and I just found this typo when the stranded guy says "Very suspicios if you ask me" https://cdn.discordapp.com/attachments/765932545908539403/781265612223414272/unknown.png
For the rest of the test no glitches in sight. I saw you took the idea about She Ra :) and what you did with the "pet the dog" was... something! I firstly had a hard time knowing how to interrupt it (IDK, I clicked random buttons, nothing happened, I waited, I clicked again and it worked, so maybe false contact?) , then I interrupted it after a couple lines, then I wanted to do as long as I could... that was quite unexpectedly creepy! They'll love it! Ah, I didn't say that yet, but nice ost!
I just tried to do the first ending again and I think the clouds are very hard to land on, it happens a lot that I  jump in the middle of the cloud and I still go through it and fall. But the dance thing is nicely allowing some mistakes. I think there is all there is to say, so just good success to your game!

**Comment by headcr4sh** [comment] 2020-11-25 22:52
Thanks for letting us know about the typo. Good catch!
Will be fixed in the next release. :-)

**Comment by Nuktos** [comment] 2020-11-27 20:05
Oh, I wasn't sure but I checked, at the start of the game when I fell from the clouds, I realised my right ear still hears faintly the soundtrack for the grotto of the start.

**Comment by Nuktos** [comment] 2020-11-27 21:16
And typo + chatbox beyond the end of the screen https://cdn.discordapp.com/attachments/314551807718457345/781991375863414804/unknown.png

**Comment by Nuktos** [comment] 2020-11-27 21:26
Note that if you just got the double jump and go see the stranded guy, you can pretend you came through the normal way and that you received the fly ability. Though it's false.

**Comment by Nuktos** [comment] 2020-11-27 22:03
Oh, and suggestion: what if you could have a different dialogue with characters if you are holding the rock character, and especially if you managed to cross the water without dropping him to talk to the second fire?

**Comment by eduke2k** [comment] 2020-11-27 23:54
> And typo + chatbox beyond the end of the screen https://cdn.discordapp.com/attachments/314551807718457345/781991375863414804/unknown.png

This looks really strange and i wasn't able to reproduce this behaviour. Seems like the dialogue data got scrambled. Can you easily reproduce this? If so, please let us know how. Just triggering this dialogue choice looks fine on my end (latest firefox and chrome)

**Comment by Nuktos** [comment] 2020-11-28 15:12
I've tried several times and didn't get to reproduce it... ¯\_(ツ)_/¯

**Comment by eduke2k** [comment] 2020-11-30 11:27
> Oh, and suggestion: what if you could have a different dialogue with characters if you are holding the rock character, and especially if you managed to cross the water without dropping him to talk to the second fire?

I added a little special dialogue for players who manage to get the stone over the river and talk to the fire :) This should be the only npc you can interact with across the river, since you can't get into the cave while carrying the stone.

**Comment by eduke2k** [comment] 2020-11-30 11:30
> Note that if you just got the double jump and go see the stranded guy, you can pretend you came through the normal way and that you received the fly ability. Though it's false.

Thanks for pointing that out! I tweaked the caveman dialogue in a way, that he reacts accordingly if you get over the river while having the double jump. Since you aren't soft locked in this scenario anymore, it will trigger the original softlock-dialogue, but with a different outcome.

**Comment by Nuktos** [comment] 2020-11-30 13:09
> > Oh, and suggestion: what if you could have a different dialogue with characters if you are holding the rock character, and especially if you managed to cross the water without dropping him to talk to the second fire?
> 
> I added a little special dialogue for players who manage to get the stone over the river and talk to the fire :) This should be the only npc you can interact with across the river, since you can't get into the cave while carrying the stone.

Great. I mean, personally I always take a full hour to cross the water if I don't have any power up, a friend now masters the trick so I asked them... And since you drop the rock when you drown it's gonna be super hard even with double jump (forcing you to start the game all over again if you fail), but it could be very funny.

**Comment by Nuktos** [comment] 2020-11-30 18:37
Oh yeah, and my friend told me "I threw everything in the water and it's funny: the skull drowns, the bone bounces, and the wood/pine cone glide to the right to be accessible. And if you throw them at the second water spot, they glide through the small island" so it's funny that you gave different properties, and it's smart to make key items not get stuck.

**Comment by Nuktos** [comment] 2020-12-01 16:39
Hi! I'm testing the new steam version!
First, the gamepad doesn't work. 
Secondly I had once again the "I hear the previous soundtrack faintly on the right", but this time after the non euclidean puzzle:

https://cdn.discordapp.com/attachments/765932656655335465/783369334566551552/friendly_fire_soundtrack_superposition2.wav

Also once, I started the game and I just dropped on the first clouds, it teleported me on the hill right above the mean fire. https://cdn.discordapp.com/attachments/765932656655335465/783371419747876964/unknown.png
And I just went in the mushrooms cave, I dropped myself to the right exit and it teleported me at that exact same spot on the hill, with the cave ost!

**Comment by eduke2k** [comment] 2020-12-01 16:53
> First, the gamepad doesn't work.
I tested it with steam as well and can confirm. Really strange. The standalone exe works fine with my dualshock but launched with the steam client, it doesn't. I have no idea what could cause that

> Secondly I had once again the "I hear the previous soundtrack faintly on the right"
Do you have, by any chance, a bad framerate when playing friendly fire? That could be the only reason why you have this music volume issue as well as the out-of-bounds resets (that's what the teleports to the main area mean). Any chance you could fin dout your frame rate when playing? Maybe by using some external software? (Fraps, or some build-in functions of steam or your graphics card)

**Comment by Nuktos** [comment] 2020-12-01 16:58
Sometimes the character doesn't dance while doing the rhythm mini game
Also, funny stuff, I tried to drop the bone at the power up dog before it's mentioned, it did nothing so I let it there and went back to talk with the dog and soon during the dialogue, I heard the sound of the power up getting the bone. Not that it's not normal, it's just funny.

**Comment by Nuktos** [comment] 2020-12-01 17:02
> > First, the gamepad doesn't work.
> 
> I tested it with steam as well and can confirm. Really strange. The standalone exe works fine with my dualshock but launched with the steam client, it doesn't. I have no idea what could cause that.
> 
> > Secondly I had once again the "I hear the previous soundtrack faintly on the right"
> 
> Do you have, by any chance, a bad framerate when playing friendly fire? That could be the only reason why you have this music volume issue as well as the out-of-bounds resets (that's what the teleports to the main area mean). Any chance you could find out your frame rate when playing? Maybe by using some external software? (Fraps, or some build-in functions of steam or your graphics card)

I don't know, I mean my computer is a potato, I can't stream or record a video of my play, and I have some very small lags (which are related to me taking a full hour trying to get past the lake). Then again, it's supposed to be a small game...

**Comment by eduke2k** [comment] 2020-12-01 17:14
> Then again, it's supposed to be a small game...

Yes, it is. But a poorly optimized one written in javascript run by an engine that was written in three days :) Issues that stem from bad performance are hard/impossible for me to fix since that would mean to refactor and/or update most of the core engine. That's not going to happen, I'm afraid (at least not by me).

**Comment by Nuktos** [comment] 2020-12-01 17:17
Okay, well I'll have my friend talk to the second fire with the stone because I can't and I'm curious 😊 I don't think I have anything left to say

**Comment by eduke2k** [comment] 2020-12-01 17:27
Thanks again for your valid feedback! I hope you can find a way to play the game with a better framerate and enjoy the two new endings as well :)

**Comment by Nuktos** [comment] 2020-12-01 17:30
> Thanks again for your valid feedback! I hope you can find a way to play the game with a better framerate and enjoy the two new endings as well :)

Wait what, TWO?! What do you mean? There are FIVE ENDINGS now???

**Comment by Nuktos** [comment] 2020-12-01 20:18
Hi my friend softlocked himself. https://cdn.discordapp.com/attachments/314551807718457345/783424166347014175/unknown.png impossible to lift Mr rock again

**Comment by eduke2k** [comment] 2020-12-01 20:26
>Hi my friend softlocked himself.

Any info on how he did it? I guess he carried the stone down and somehow could throw it NOT into the river? :D

**Comment by Nuktos** [comment] 2020-12-01 20:36
He dropped Mr rock not far enough so he fell on the floor, so he's not in the water

**Comment by Nuktos** [comment] 2020-12-01 21:34
The fire acted like he still had the rock on his head, and there wasn't the success sound like if he was in the water. But he could just go to the fire with the rock guy then throw the rock in the water

**Comment by Nuktos** [comment] 2020-12-04 18:22
Just so you know, you can talk to the bird on her nest, where she has the same dialogue, including "you can visit us at our nest, if you can fly that is"
Also I had a bad frame teleport in the "softlock" cave up to the first hill and I found it very funny. That could be his solution 😅
And I'm still searching for the fifth ending.

**Comment by Nuktos** [comment] 2020-12-04 18:39
https://cdn.discordapp.com/attachments/765932656655335465/784488798712889364/unknown.png you guys are insane 😂👌

**Comment by Nuktos** [comment] 2020-12-05 01:19
I don't know if you intended to make some characters like shadow guy, the "friendly fire" or the tree disappear when you engage ending E, but I checked and they did, as well as the flying power. Then I went through the portal and went all to the right of the ship, and my bad frame rate made this happen: https://cdn.discordapp.com/attachments/765932656655335465/784587718218743829/unknown.png https://cdn.discordapp.com/attachments/765932656655335465/784587763088490516/unknown.png
Since I'm that character, I can't even jump so I'm softlocked😅.

**Comment by headcr4sh** [comment] 2021-02-15 10:08
This Issue has become some kind of lengthy discussion.
I am therefore closing it.

@Nuktos Thanks for all your input and feedback.
If you feel that any issue or problem still persists and should be fixed, you can create a *new* issue at any time. Please keep in mind though, that "one github issue per game issue" is the way to go here. Discussions about the game should go someplace else (we haven't figured out *where* exactly discussions should take place, but email or the Steam discussion board are probably better suited than an issue tracker)

**Closed by headcr4sh** 2021-02-15 10:08 UTC
